which eza 2>/dev/null; and alias ls 'eza'
alias l  'ls'
alias ll 'ls -lghB --git'
alias la 'ls -lghBa --git'
alias lt 'ls -lghB --git --tree'
alias df 'df -h'
alias du 'du -h'
alias ip 'ip --color'
alias i3lock 'i3lock -c 000000'
